Sheethost upload

diff --git a/bemuse b/bemuse
--- a/bemuse
+++ b/bemuse
@@ -1,7 +1,7 @@
 #!/bin/bash
 set -e
 
-USAGE="usage: $0 [--directory=<directory>] [--state=<state>] [--width=<px>] [--height=<px>] [--framerate=<fps>] [--chroma=<ffmpeg-input>] [--colorkey=<ffmpeg-colorkey>] [--scale=<ffmpeg-scale>] [--overlay=<ffmpeg-overlay>] [--filter=<ffmpeg-filter>] [--fade=<sec>] [--audio-offset=<sec>] [--video-offset=<sec>] [--duration=<sec>] [--thumbnail-from=<sec>] [--thumbnail-to=<sec>] [--thumbnail-convert=<convert-options>] [--skip-video] [--visualize] [--keep] <score>"
+USAGE="usage: $0 [--directory=<directory>] [--state=<state>] [--width=<px>] [--height=<px>] [--framerate=<fps>] [--chroma=<ffmpeg-input>] [--colorkey=<ffmpeg-colorkey>] [--scale=<ffmpeg-scale>] [--overlay=<ffmpeg-overlay>] [--filter=<ffmpeg-filter>] [--fade=<sec>] [--audio-offset=<sec>] [--video-offset=<sec>] [--duration=<sec>] [--thumbnail-from=<sec>] [--thumbnail-to=<sec>] [--thumbnail-convert=<convert-options>] [--sheethost-metadata=<metadata>] [--sheethost-username=<username>] [--sheethost-password=<password>] [--skip-video] [--visualize] [--keep] <score>"
 WIDTH=1920
 HEIGHT=1080
 FRAMERATE=60
@@ -21,28 +21,31 @@ while getopts :-: OPT; do
     OPTARG="${OPTARG#=}"
   fi
   case "$OPT" in
-    directory )         needs_arg; DIRECTORY="$OPTARG" ;;
-    state )             needs_arg; STATE="$OPTARG" ;;
-    width )             needs_arg; WIDTH="$OPTARG" ;;
-    height )            needs_arg; HEIGHT="$OPTARG" ;;
-    framerate )         needs_arg; FRAMERATE="$OPTARG" ;;
-    chroma )            needs_arg; CHROMA="$OPTARG" ;;
-    colorkey )          needs_arg; COLORKEY="$OPTARG" ;;
-    scale )             needs_arg; SCALE="$OPTARG" ;;
-    overlay )           needs_arg; OVERLAY="$OPTARG" ;;
-    filter )            needs_arg; FILTER="$OPTARG" ;;
-    fade )              needs_arg; FADE="$OPTARG" ;;
-    audio-offset )      needs_arg; AUDIO_OFFSET="$OPTARG" ;;
-    video-offset )      needs_arg; VIDEO_OFFSET="$OPTARG" ;;
-    duration )          needs_arg; DURATION="$OPTARG" ;;
-    thumbnail-from )    needs_arg; THUMBNAIL_FROM="$OPTARG" ;;
-    thumbnail-to )      needs_arg; THUMBNAIL_TO="$OPTARG" ;;
-    thumbnail-convert ) needs_arg; THUMBNAIL_CONVERT="$OPTARG" ;;
-    skip-video )        SKIP_VIDEO=true ;;
-    visualize )         VISUALIZE=true ;;
-    keep )              KEEP=true ;;
-    ??* )               die "Illegal option --$OPT" ;;
-    \? )                die $USAGE ;;
+    directory )          needs_arg; DIRECTORY="$OPTARG" ;;
+    state )              needs_arg; STATE="$OPTARG" ;;
+    width )              needs_arg; WIDTH="$OPTARG" ;;
+    height )             needs_arg; HEIGHT="$OPTARG" ;;
+    framerate )          needs_arg; FRAMERATE="$OPTARG" ;;
+    chroma )             needs_arg; CHROMA="$OPTARG" ;;
+    colorkey )           needs_arg; COLORKEY="$OPTARG" ;;
+    scale )              needs_arg; SCALE="$OPTARG" ;;
+    overlay )            needs_arg; OVERLAY="$OPTARG" ;;
+    filter )             needs_arg; FILTER="$OPTARG" ;;
+    fade )               needs_arg; FADE="$OPTARG" ;;
+    audio-offset )       needs_arg; AUDIO_OFFSET="$OPTARG" ;;
+    video-offset )       needs_arg; VIDEO_OFFSET="$OPTARG" ;;
+    duration )           needs_arg; DURATION="$OPTARG" ;;
+    thumbnail-from )     needs_arg; THUMBNAIL_FROM="$OPTARG" ;;
+    thumbnail-to )       needs_arg; THUMBNAIL_TO="$OPTARG" ;;
+    thumbnail-convert )  needs_arg; THUMBNAIL_CONVERT="$OPTARG" ;;
+    sheethost-metadata ) needs_arg; SHEETHOST_METADATA="$OPTARG" ;;
+    sheethost-username ) needs_arg; SHEETHOST_USERNAME="$OPTARG" ;;
+    sheethost-password ) needs_arg; SHEETHOST_PASSWORD="$OPTARG" ;;
+    skip-video )         SKIP_VIDEO=true ;;
+    visualize )          VISUALIZE=true ;;
+    keep )               KEEP=true ;;
+    ??* )                die "Illegal option --$OPT" ;;
+    \? )                 die $USAGE ;;
   esac
 done
 shift $((OPTIND-1))
@@ -51,6 +54,7 @@ SCORE=$@
 if [[ -z "$SCORE" ]];                     then die $USAGE; fi
 if [[ ! -f "$SCORE" ]];                   then die "Score $SCORE does not exist."; fi
 if ! command -v convert > /dev/null;      then die "ImageMagick not installed."; fi
+if ! command -v jq > /dev/null;           then die "jq not installed."; fi
 if command -v ffmpeg > /dev/null;         then FFMPEG=ffmpeg; fi
 if command -v ffmpeg.exe > /dev/null;     then FFMPEG=ffmpeg.exe; fi
 if [[ -z $FFMPEG ]];                      then die "ffmpeg not found, check PATH!"; fi
@@ -172,6 +176,86 @@ if [[ -z $SKIP_VIDEO ]] && ([[ -z $KEEP ]] || [[ ! -f "$BASE.thumbnail.jpg" ]]);
     convert "$BASE.thumbnail.jpg" $THUMBNAIL_CONVERT "$BASE.thumbnail.jpg"
 else
     echo "Keeping thumbnail."
+fi
+
+if [[ ! -z $SHEETHOST_METADATA ]] && [[ ! -z $SHEETHOST_USERNAME ]] && [[ ! -z $SHEETHOST_PASSWORD ]]; then
+    echo "Uploading to Sheethost ..."
+    if [[ -f $SHEETHOST_METADATA ]]; then
+        source "$SHEETHOST_METADATA"
+    fi
+    if [[ -z $TITLE ]] || [[ -z $COMPOSER ]] || [[ -z $INSTRUMENTS ]]; then
+        echo "Could not find sheet metadata, skipping upload."
+        # sheet metadata should set the following variables:
+        # TITLE="Song Title"
+        # SOURCE_TITLE="Where's it from?"
+        # COMPOSER="Composer(s)"
+        # CREATOR_NAME="Arranger/Transcriber"
+        # ARTIST="Original Artist/Performer"
+        # COPYRIGHT="Copyright Year & Name"
+        # DESCRIPTION="Description"
+        # TAGS="" # comma-separated list of tags
+        # TYPE_ID=1 # arrangement, 2 = official release, 3 = original work, 4 = transcription, 5 = other
+        # CATEGORY_ID=1 # video game
+        # INSTRUMENTS=57 # piano
+        # PAGES=1 # number of pages
+        # DIFFICULTY=1 # 1 = easy, 2 = moderate, 3 = intermediate, 4 = proficient, 5 = advanced, 6 = insane
+        # PRIVACY_STATUS=1 # 1 = public, 2 = unlisted, 3 = private
+    else
+        if [[ -z $PAGES ]]; then
+            PAGES=$(strings < "$BASE.pdf" | sed -n "s|.*/Count -\{0,1\}\([0-9]\{1,\}\).*|\1|p" | sort -rn | head -n1)
+        fi
+        RES=$(curl -c "$BASE.session" \
+            --data-urlencode "login=$SHEETHOST_USERNAME" \
+            --data-urlencode "password=$SHEETHOST_PASSWORD" \
+            https://sheet.host/account/login)
+        trap 'rm -f "$BASE.session"' EXIT
+        if [[ ! -z $RES ]]; then
+            echo "Could not log in to Sheethost, skipping upload."
+        else
+            echo "Creating sheet ..."
+            RES=$(curl -X PUT -b "$BASE.session" -H "X-Requested-With: XMLHttpRequest" \
+                --data-urlencode "title=$TITLE" \
+                --data-urlencode "source_title=$SOURCE_TITLE" \
+                --data-urlencode "composer=$COMPOSER" \
+                --data-urlencode "creator_name=$CREATOR_NAME" \
+                --data-urlencode "artist=$ARTIST" \
+                --data-urlencode "copyright=$COPYRIGHT" \
+                --data-urlencode "description=$DESCRIPTION" \
+                --data-urlencode "tags=$TAGS" \
+                --data-urlencode "type_id=$TYPE_ID" \
+                --data-urlencode "category_id=$CATEGORY_ID" \
+                --data-urlencode "instruments[]=$INSTRUMENTS" \
+                --data-urlencode "pages=$PAGES" \
+                --data-urlencode "difficulty=$DIFFICULTY" \
+                --data-urlencode "privacy_status=$PRIVACY_STATUS" \
+                https://sheet.host/api/score/resource)
+            echo $RES
+            ID=$(echo $RES | jq -r '.sheet.id')
+            HASH=$(echo $RES | jq -r '.sheet.hash')
+
+            upload_file() {
+                echo "Uploading $1 ..."
+                curl -F "files[]=@$1" -b "$BASE.session" -H "X-Requested-With: XMLHttpRequest" https://sheet.host/api/score/file//$ID
+                echo
+            }
+
+            upload_file "$BASE.jpg"
+            upload_file "$BASE.pdf"
+            upload_file "$BASE.mid"
+            upload_file "$BASE.mscz"
+
+            echo "Publishing sheet ..."
+            curl -b "$BASE.session" -H "X-Requested-With: XMLHttpRequest" \
+                --data-urlencode "id=$ID" \
+                --data-urlencode "notify_followers=0" \
+                https://sheet.host/api/score/publish
+
+            echo
+            echo "Sheet published at: https://sheet.host/sheet/$HASH"
+        fi
+    fi
+else
+    echo "Skipping Sheethost upload."
 fi
 
 echo "Done."
